/**
 * Adeptra Merchant — robots.txt Patch Artifact Generator (artifact_type = 'robots_patch').
 *
 * PURE module: reads ctx.robots/ctx.parsedRobots (already fetched by
 * readabilityChecks.ts's runReadabilityChecks — never re-fetched here) plus
 * ctx.signals and ctx.signalEvidence. No network, no DB.
 *
 * IT IS A PATCH, NOT A REPLACEMENT FILE (except when the file is missing
 * entirely — nothing to preserve, so a full file is safe). An existing
 * robots.txt may contain rules this codebase doesn't understand (admin
 * paths, crawl-delay, etc.) — wholesale rewriting risks silently destroying
 * them. `content` is therefore written as PLAIN-ENGLISH REMOVE/ADD
 * instructions, formatted using `#` comments so the file is syntactically
 * valid (inert) robots.txt even if a merchant panics and deploys it as-is —
 * the worst case is harmless comments, never a silently broken file. This
 * also keeps target_url "/robots.txt" honest: filenameForArtifact() names
 * the bundled file "robots.txt", and a self-documenting "DO NOT REPLACE"
 * header at the very top is what makes that filename not misleading.
 *
 * WILDCARD SAFETY: when a retrieval bot is blocked via `User-agent: *`
 * (shared with every other crawler, not just AI ones), this generator NEVER
 * proposes removing that rule — doing so would unblock Googlebot, Bingbot,
 * everything, a far bigger and unrelated decision than "allow AI answer-
 * citation crawlers." Instead it proposes ADDING a new bot-specific
 * `User-agent: <bot>\nAllow: /` override group, which — per standard
 * robots.txt precedence (an exact-token match always beats the wildcard,
 * see readabilityChecks.ts's findGroupForToken) — unblocks that one bot
 * without touching the wildcard rule at all. Removal is only proposed when
 * the blocking rule lives in a bot-specific group (touching it only ever
 * affects that one bot).
 *
 * MERCHANT-INTENT RULE (identity_linking lesson, third application):
 * training-bot (GPTBot/ClaudeBot) directives are NEVER added to or removed
 * by this generator, regardless of ai_training_opt_out. Blocking them keeps
 * a merchant's content out of model training — a legitimate IP decision,
 * not a bug. If opted out, we say so and touch nothing. If not opted out and
 * they're blocked anyway, we FLAG it (changelog.flagged, never .added) and
 * present both sides — the merchant decides, we don't auto-unblock.
 *
 * robots_txt_valid's "malformed, but a file exists" (partial) case is
 * flagged, not patched — we can't safely emit a scoped fix for content we
 * don't recognize. Only the "file is missing entirely" (fail) case resolves
 * robots_txt_valid, via the full-file path.
 */

import type { SignalRow } from "../manifestChecks.ts";
import type { ArtifactContext, ArtifactDraft, ArtifactChangelog } from "./types.ts";
import { findBlockingRule, findGroupForToken, type ParsedRobots, type RobotsRule } from "../readabilityChecks.ts";

const TARGET_URL = "/robots.txt";
const RETRIEVAL_BOTS = ["OAI-SearchBot", "Claude-SearchBot", "PerplexityBot"];
const TRAINING_BOTS = ["GPTBot", "ClaudeBot"];

function byKey(signals: SignalRow[]): Map<string, SignalRow> {
  return new Map(signals.map((s) => [s.signal_key, s]));
}

function needsFix(s: SignalRow | undefined): boolean {
  return s?.status === "fail" || s?.status === "partial";
}

function rawLineText(raw: string | null, lineNumber: number): string {
  if (!raw) return "";
  const lines = raw.split(/\r?\n/);
  return (lines[lineNumber - 1] ?? "").trim();
}

// ---------------------------------------------------------------------------
// Per-bot unblock plan
// ---------------------------------------------------------------------------

type BotAction =
  | { bot: string; kind: "already_allowed" }
  | { bot: string; kind: "remove_specific"; rule: RobotsRule }
  | { bot: string; kind: "add_override" };

function planBotUnblock(parsedRobots: ParsedRobots, bot: string): BotAction {
  const rule = findBlockingRule(parsedRobots, bot);
  if (!rule) return { bot, kind: "already_allowed" };
  const group = findGroupForToken(parsedRobots.groups, bot);
  const isWildcardGroup = !!group && group.userAgents.some((ua) => ua === "*");
  return isWildcardGroup ? { bot, kind: "add_override" } : { bot, kind: "remove_specific", rule };
}

// ---------------------------------------------------------------------------
// Content builders
// ---------------------------------------------------------------------------

function fullMinimalFile(): string {
  return [
    "# Generated by Adeptra Merchant.",
    "# No robots.txt was found at this domain. A missing file already means",
    '# "allow everything" to every crawler, so this file adds explicitness,',
    "# not a new restriction.",
    "User-agent: *",
    "Allow: /",
    "",
  ].join("\n");
}

function patchInstructions(removals: { line: number; text: string }[], additions: string[][]): string {
  const lines: string[] = [
    "# ADEPTRA MERCHANT — robots.txt PATCH INSTRUCTIONS",
    "# Do NOT replace your existing robots.txt with this file.",
    "# Apply these changes to your EXISTING file by hand. Everything else in",
    "# your file is untouched — only the lines named below are affected.",
  ];
  if (removals.length === 0 && additions.length === 0) {
    lines.push("#", "# No file changes are needed — see the notes below for what to consider.");
    return lines.join("\n") + "\n";
  }
  if (removals.length > 0) {
    lines.push("#", "# REMOVE:");
    for (const r of removals) lines.push(`#   line ${r.line}: ${r.text}`);
  }
  if (additions.length > 0) {
    lines.push("#", "# ADD (e.g. at the end of the file):");
    for (const block of additions) {
      for (const l of block) lines.push(`#   ${l}`);
      lines.push("#");
    }
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

export function generateRobotsPatchArtifact(ctx: ArtifactContext): ArtifactDraft | null {
  const { signals, robots, parsedRobots, signalEvidence } = ctx;
  if (!robots || !parsedRobots) return null; // defensive — pipeline.ts always sets these

  const sig = byKey(signals);
  const robotsValid = sig.get("robots_txt_valid");
  const retrieval = sig.get("ai_crawler_access_retrieval");
  const training = sig.get("ai_crawler_access_training");

  const anythingToFix = needsFix(robotsValid) || needsFix(retrieval) || needsFix(training);
  if (!anythingToFix) return null;

  const changelog: ArtifactChangelog = { added: [], corrected: [], must_complete: [], flagged: [] };
  const resolvedKeys: string[] = [];

  const fileMissing = !robots.reachable || robots.httpStatus == null || robots.httpStatus < 200 || robots.httpStatus >= 300;
  let content: string;

  if (fileMissing) {
    content = fullMinimalFile();
    changelog.added.push("A minimal robots.txt allowing all crawlers, including the AI answer-citation bots (OAI-SearchBot, Claude-SearchBot, PerplexityBot).");
    if (needsFix(robotsValid)) resolvedKeys.push("robots_txt_valid");
    // A missing file blocks nothing (see isUserAgentBlocked's semantics), so
    // ai_crawler_access_retrieval can't have been failing at the same time —
    // nothing further to resolve here.
  } else {
    if (robotsValid?.status === "partial") {
      changelog.flagged.push(
        "robots.txt exists but has no recognizable User-agent/Disallow/Sitemap directives — Adeptra can't safely patch content it doesn't understand. Review and fix the file's format manually.",
      );
    }

    const retrievalActions = needsFix(retrieval) ? RETRIEVAL_BOTS.map((b) => planBotUnblock(parsedRobots, b)).filter((a) => a.kind !== "already_allowed") : [];

    const removalsMap = new Map<number, { line: number; text: string }>();
    for (const a of retrievalActions) {
      if (a.kind === "remove_specific") {
        removalsMap.set(a.rule.line, { line: a.rule.line, text: rawLineText(robots.raw, a.rule.line) });
      }
    }
    const additions: string[][] = retrievalActions.filter((a) => a.kind === "add_override").map((a) => [`User-agent: ${a.bot}`, "Allow: /"]);

    content = patchInstructions(Array.from(removalsMap.values()), additions);

    if (retrievalActions.length > 0) {
      const removedBots = retrievalActions.filter((a) => a.kind === "remove_specific").map((a) => a.bot);
      const addedBots = retrievalActions.filter((a) => a.kind === "add_override").map((a) => a.bot);
      if (removedBots.length > 0) changelog.added.push(`Removes the bot-specific Disallow rule blocking: ${removedBots.join(", ")}.`);
      if (addedBots.length > 0) {
        changelog.added.push(
          `Adds a bot-specific Allow override for: ${addedBots.join(", ")} — these are currently blocked by your wildcard (User-agent: *) rule, which is left untouched since it also governs every other crawler.`,
        );
      }
      changelog.must_complete.push(
        "Deploying this patch allows OAI-SearchBot/Claude-SearchBot/PerplexityBot to fetch your pages for AI-generated answer citations — a choice you're making by applying it.",
      );
      const retrievalNote = signalEvidence?.get("ai_crawler_access_retrieval")?.merchant_note;
      if (retrievalNote) changelog.flagged.push(retrievalNote);
      resolvedKeys.push("ai_crawler_access_retrieval");
    }
  }

  // --- ai_crawler_access_training: never touched, always explained ---------
  const trainingOptedOut = !!(training?.evidence_json as any)?.ai_training_opt_out;
  const trainingBlockedCount = (training?.evidence_json as any)?.blocked_count ?? 0;
  if (trainingOptedOut) {
    changelog.flagged.push(
      "GPTBot/ClaudeBot training-crawler directives were NOT touched by this patch — this site has attested (ai_training_opt_out) that keeping its content out of AI model training is intentional.",
    );
  } else if (trainingBlockedCount > 0) {
    changelog.flagged.push(
      `${TRAINING_BOTS.filter((b) => findBlockingRule(parsedRobots, b)).join(", ") || "GPTBot/ClaudeBot"} ${trainingBlockedCount === 1 ? "is" : "are"} blocked in your robots.txt, which keeps your content out of AI model training — a legitimate choice, not a bug. This patch does NOT unblock them. Blocking training crawlers does not affect your eligibility for AI-generated answer citations, which is governed separately by the retrieval crawlers above. If you want to allow AI training too, that's a decision to make and apply yourself — Adeptra won't make it for you.`,
    );
  }

  if (changelog.added.length === 0 && changelog.corrected.length === 0 && changelog.flagged.length === 0) return null;

  return {
    artifact_type: "robots_patch",
    target_url: TARGET_URL,
    content,
    resolves_signal_keys: resolvedKeys,
    changelog,
  };
}
