/**
 * Adeptra Merchant — Custom (bespoke store) MCP scaffold provider.
 *
 * NOT LIKE THE OTHER PROVIDERS: WooCommerce and Wix have a real, documented
 * API this generator can call. A bespoke store has none — there is no
 * platform to write a client against. So this provider does not generate a
 * working server; it generates a REFERENCE IMPLEMENTATION: a correct,
 * complete, boundary-safe, UCP-shaped MCP shopping server with the
 * store-specific data access left as clearly-marked integration points
 * (src/store.ts). It is ~80% complete and honest about the 20% only the
 * store's own developer can supply — its audience is a developer (the
 * merchant's, or Adeptra's own setup service acting for one), not a
 * merchant clicking "deploy." It must never pretend to run out of the box;
 * that would violate every honesty rule elsewhere in this codebase (see
 * mcpScaffoldArtifact.ts's header, manifestArtifact.ts's header).
 *
 * CANONICAL UCP TOOL SURFACE: search_catalog, lookup_catalog, get_product,
 * create_cart, get_cart, update_cart, cancel_cart — implemented generically
 * in scaffold/shared.ts's mcpToolsTs() (session state machine, diff-and-
 * reconcile, continue_url caching, the not_found business-outcome shape).
 * src/server.ts (complete, do not edit) wires the StoreAdapter's methods
 * into this shared tool set — a developer only ever touches src/store.ts.
 *
 * THE BOUNDARY HERE IS A CONTRACT, NOT CODE THAT CALLS A REAL API: the
 * StoreAdapter interface (src/types.ts) has no payment method, no order-
 * creation method, no customer/admin method — that absence IS the boundary.
 * getCheckoutUrl()'s own doc comment states outright what it must not do.
 * A developer COULD violate this by adding a payment method to the
 * interface — the contract says not to, loudly, but (unlike WooCommerce's
 * API-shape enforcement or Wix's discipline-in-generated-code) nothing here
 * can stop a developer from ignoring it. Documented as such, not hidden.
 * emptyCart() is a genuine addition to the contract this round (needed for
 * the session state machine's create_cart/cancel_cart guarantees) — it's a
 * cart operation, not an order one, so it doesn't change that boundary.
 *
 * server.ts (complete, the developer should not need to edit it) refuses to
 * start if store.ts is still unimplemented — detected by a static check of
 * each StoreAdapter method's own source text for the literal "IMPLEMENT-THIS"
 * marker every stub throws (see unimplementedMethodsTs() below for why this
 * is a live-invoke-and-catch or a separate flag would both be worse).
 */

import type { ArtifactContext, ArtifactFile } from "../types.ts";
import {
  TARGET_FOLDER,
  MCP_SDK_VERSION,
  ZOD_VERSION,
  storeLabel,
  tsconfigJson,
  loadEnvTs,
  mcpToolsTs,
  ucpConformanceDisclosure,
  type ScaffoldProvider,
} from "./shared.ts";

const STORE_BASE_URL_PLACEHOLDER = "https://REPLACE-WITH-YOUR-STORE-URL.example";
const CHECKOUT_URL_PLACEHOLDER = "https://REPLACE-WITH-YOUR-CHECKOUT-URL.example";

function packageJson(): string {
  return (
    JSON.stringify(
      {
        name: "custom-mcp-shopping-server",
        version: "1.0.0",
        private: true,
        type: "module",
        description:
          "MCP shopping server REFERENCE IMPLEMENTATION for a custom/bespoke store — UCP catalog + cart, with store-specific data access left as an integration point (src/store.ts). Not runnable until that adapter is implemented. Generated by Adeptra Merchant.",
        engines: { node: ">=18" },
        scripts: {
          build: "tsc",
          start: "node dist/server.js",
          dev: "tsc --watch",
        },
        dependencies: {
          "@modelcontextprotocol/sdk": MCP_SDK_VERSION,
          zod: ZOD_VERSION,
        },
        devDependencies: {
          typescript: "^5.7.0",
          "@types/node": "^22.0.0",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function envExample(): string {
  return [
    `STORE_BASE_URL=${STORE_BASE_URL_PLACEHOLDER}`,
    `CHECKOUT_URL=${CHECKOUT_URL_PLACEHOLDER}`,
    "",
    "# This scaffold reads no other environment variables by default. Add",
    "# whatever credentials YOUR store's API needs (API keys, tokens, session",
    "# secrets, etc.) once you implement src/store.ts against your own store —",
    "# this file is a starting point, not an exhaustive list.",
    "",
  ].join("\n");
}

function typesTs(): string {
  return `/**
 * THE ADAPTER CONTRACT. This file IS the spec src/store.ts implements
 * against — read it fully before touching store.ts.
 *
 * WHAT THIS INTERFACE DELIBERATELY DOES NOT HAVE: any payment method, any
 * order-creation method, any customer/admin method. That absence is this
 * server's entire payment/order boundary — see getCheckoutUrl's own doc
 * comment below. This interface intentionally cannot express payment
 * authorization. If you find yourself needing to add such a method here,
 * STOP — that is outside this server's scope. Payment and order placement
 * belong on your own checkout page, reached via the URL getCheckoutUrl()
 * returns, never in this adapter.
 */

export interface Product {
  id: string;
  title: string;
  description: string;
  /** A decimal amount as a string, e.g. "19.99" — no currency symbol. */
  price: string;
  /** ISO 4217 currency code, e.g. "USD". */
  currency: string;
  inStock: boolean;
  /** Link to this product's page on your store, if it has one. Optional. */
  url?: string;
}

export interface CartLineItem {
  /** A stable id for THIS LINE ITEM — not the product id. Returned by
   *  addToCart, then used by updateCartItem/removeCartItem to identify
   *  which line to change. If your cart layer doesn't have a natural line
   *  item id, the product id is an acceptable stand-in ONLY if a cart can
   *  never hold the same product twice as separate lines. */
  id: string;
  productId: string;
  title: string;
  quantity: number;
  /** This line's unit price, same format as Product.price. */
  price: string;
}

export interface Cart {
  id: string;
  lineItems: CartLineItem[];
  currency: string;
  /** The cart's total, if your store can compute one cheaply. Optional —
   *  callers should sum lineItems themselves if this is omitted. */
  total?: string;
}

/**
 * The eight methods server.ts (complete, do not edit) calls and nothing
 * else. Implement each against your own store's product/cart layer — see
 * src/store.ts for a stub of every method with a worked example.
 */
export interface StoreAdapter {
  /** Return up to \`limit\` products matching \`query\`. Return an empty
   *  array for "no results" — never throw for that case. */
  searchProducts(query: string, limit: number): Promise<Product[]>;
  /** Return full details for one product by id. Throw a real Error (any
   *  message) if the id doesn't exist. */
  getProduct(id: string): Promise<Product>;
  /** Return the current shopper's cart. If none exists yet, return an
   *  empty one (lineItems: []) — that's a normal state, not an error. */
  getCart(): Promise<Cart>;
  /** Add \`quantity\` of product \`productId\` to the cart (creating the cart
   *  if needed) and return the resulting cart. */
  addToCart(productId: string, quantity: number): Promise<Cart>;
  /** Change the quantity of the cart line item \`lineItemId\` (NOT a product
   *  id — see CartLineItem.id above) and return the resulting cart. */
  updateCartItem(lineItemId: string, quantity: number): Promise<Cart>;
  /** Remove the cart line item \`lineItemId\` and return the resulting cart. */
  removeCartItem(lineItemId: string): Promise<Cart>;
  /** Remove EVERY line item from the cart — a real, total removal (not a
   *  session-state flag). Used both to guarantee a truly empty starting
   *  cart and to make cart cancellation genuine, not just pretended. Return
   *  the resulting (now empty) cart. */
  emptyCart(): Promise<Cart>;
  /**
   * Return a URL where the shopper completes their purchase on YOUR store's
   * own checkout, for the current cart.
   *
   * This method must NOT authorize, capture, or process payment. Return a
   * URL where the shopper completes payment on your own checkout, exactly
   * as they would normally — the same URL you'd hand a shopper who filled a
   * cart on your website directly. Do not collect card details, call a
   * payment processor, or create a completed order in this method.
   */
  getCheckoutUrl(): Promise<string>;
}
`;
}

function storeTs(): string {
  return `import type { StoreAdapter, Product, Cart } from "./types.js";

/**
 * THE INTEGRATION POINT. Every method below throws a placeholder error —
 * that's intentional: this scaffold cannot know your store's stack, so it
 * cannot generate a working client for it. Replace each throw with real
 * code against your own store's product/cart layer. See README.md for the
 * recommended implementation order and how to test each method alone.
 *
 * A plain object implementing StoreAdapter (not a class) — call these
 * directly, e.g. \`await storeAdapter.getProduct("123")\`, to test one
 * method at a time before wiring up the full server.
 */
export const storeAdapter: StoreAdapter = {
  /**
   * Expected return shape:
   *   [{ id: "123", title: "Blue T-Shirt", description: "100% cotton",
   *      price: "19.99", currency: "USD", inStock: true,
   *      url: "https://yourstore.example.com/products/123" }]
   */
  async searchProducts(query: string, limit: number): Promise<Product[]> {
    /* Example (generic REST) — replace this ENTIRE function body with real
     * code; this comment block is guidance, not a working implementation:
     *
     *   const res = await fetch(
     *     \`\${process.env.STORE_BASE_URL}/api/products?q=\${encodeURIComponent(query)}&limit=\${limit}\`,
     *   );
     *   const data = await res.json();
     *   return data.products.map((p: any) => ({
     *     id: String(p.id),
     *     title: p.name,
     *     description: p.description ?? "",
     *     price: String(p.price),
     *     currency: p.currency ?? "USD",
     *     inStock: p.stock_quantity > 0,
     *     url: p.url,
     *   }));
     *
     * The same fetch-your-API-then-map-to-the-contract pattern applies to
     * every method below — it isn't repeated for each one.
     */
    throw new Error(
      "IMPLEMENT-THIS: return up to 'limit' products matching 'query' from your store's catalog. Never throw for zero results — return []. See this method's doc comment above and src/types.ts's Product type for the exact shape.",
    );
  },

  /**
   * Expected return shape: a single Product object (see searchProducts'
   * example above for the field shape). Throw a real Error if \`id\` doesn't
   * exist in your catalog.
   */
  async getProduct(id: string): Promise<Product> {
    throw new Error(
      "IMPLEMENT-THIS: return full details for the product with this id, or throw if it doesn't exist. See src/types.ts's Product type for the exact shape.",
    );
  },

  /**
   * Expected return shape:
   *   { id: "cart_abc", lineItems: [], currency: "USD" }
   * for an empty/new cart, or with real CartLineItem entries once
   * populated. Return an empty cart rather than throwing when none exists.
   */
  async getCart(): Promise<Cart> {
    throw new Error(
      "IMPLEMENT-THIS: return the current cart, or an empty one (lineItems: []) if none exists yet — never throw for that case. See src/types.ts's Cart type for the exact shape.",
    );
  },

  /** Add \`quantity\` of product \`productId\` to the cart (creating the cart
   *  if it doesn't exist yet) and return the resulting Cart. */
  async addToCart(productId: string, quantity: number): Promise<Cart> {
    throw new Error(
      "IMPLEMENT-THIS: add 'quantity' of product 'productId' to the cart (creating it if needed) and return the resulting cart. See src/types.ts's Cart type for the exact shape.",
    );
  },

  /** Change the quantity of cart line item \`lineItemId\` (NOT a product id
   *  — see CartLineItem.id in src/types.ts) and return the resulting Cart. */
  async updateCartItem(lineItemId: string, quantity: number): Promise<Cart> {
    throw new Error(
      "IMPLEMENT-THIS: change the quantity of the cart line item 'lineItemId' and return the resulting cart. See src/types.ts's CartLineItem type — 'lineItemId' is a LINE ITEM id, not a product id.",
    );
  },

  /** Remove cart line item \`lineItemId\` and return the resulting Cart. */
  async removeCartItem(lineItemId: string): Promise<Cart> {
    throw new Error(
      "IMPLEMENT-THIS: remove the cart line item 'lineItemId' and return the resulting cart. See src/types.ts's CartLineItem type — 'lineItemId' is a LINE ITEM id, not a product id.",
    );
  },

  /** Remove EVERY line item — a real, total removal, not a flag. Return the
   *  resulting (now empty) cart. */
  async emptyCart(): Promise<Cart> {
    throw new Error(
      "IMPLEMENT-THIS: remove every line item from the cart for real and return the resulting (now empty) cart. See src/types.ts's Cart type for the exact shape.",
    );
  },

  /**
   * Return a URL where the shopper completes their purchase on YOUR store's
   * own checkout, for the current cart.
   *
   * This method must NOT authorize, capture, or process payment. Return a
   * URL where the shopper completes payment on your own checkout, exactly
   * as they would normally. Do not call a payment processor, collect card
   * details, or create a completed order here — that is outside this
   * server's scope. If you find yourself needing to add such logic, stop:
   * it belongs on your own checkout page, not in this adapter. (This is the
   * same boundary WooCommerce's and Wix's generated servers enforce with
   * real API-call restrictions — here it's enforced by this contract, and
   * by you honoring it.)
   */
  async getCheckoutUrl(): Promise<string> {
    throw new Error(
      "IMPLEMENT-THIS: return a URL where the shopper completes payment on YOUR OWN checkout for the current cart. Must NOT process payment itself — see this method's doc comment and README.md's hard-boundary section before implementing.",
    );
  },
};
`;
}

function serverTs(): string {
  return `/**
 * Adeptra Merchant — Custom Store MCP Shopping Server (REFERENCE IMPLEMENTATION).
 *
 * This file is COMPLETE and correct — you should not need to edit it. It
 * wires src/store.ts's StoreAdapter into UCP's canonical catalog + cart
 * tool set (search_catalog, lookup_catalog, get_product, create_cart,
 * get_cart, update_cart, cancel_cart — see mcpTools.ts), and refuses to
 * start until that adapter is actually implemented (see the startup check
 * below). HARD BOUNDARY: this server never processes payment — every cart
 * response's continue_url comes from your adapter's getCheckoutUrl() and
 * that's as far as this server goes. See src/types.ts's StoreAdapter
 * interface for exactly why that boundary can't be expressed any other way
 * here, and README.md's "About UCP protocol conformance" section for
 * exactly what is and isn't UCP-conformant here.
 */

import "./loadEnv.js"; // MUST be the first import — see loadEnv.ts's header

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { registerUcpTools } from "./mcpTools.js";
import { storeAdapter } from "./store.js";
import type { StoreAdapter, Cart } from "./types.js";

const STUB_MARKER = "IMPLEMENT-THIS";

/**
 * Detects an unimplemented adapter WITHOUT calling it: reads each method's
 * own source text for the literal marker every stub throws, rather than
 * invoking the method and catching. Invoking would risk two failure modes
 * on a PARTIALLY implemented adapter — a real call could have a genuine
 * side effect, or throw an unrelated real error this check would then
 * misreport as "still unimplemented." A separate boolean flag was also
 * considered and rejected: it's a second thing to forget to update, and can
 * drift out of sync with what's actually implemented. Reading source text
 * can't drift — it's checking the actual current behavior, not a stated
 * belief about it. Function.prototype.toString() returns real source text
 * (not minified/stripped) for ordinary async functions/methods, so this
 * survives even if store.ts's comments are stripped by some future build
 * step — the marker lives inside the THROWN STRING LITERAL itself, not a
 * comment, specifically so this keeps working either way.
 */
function unimplementedMethods(adapter: StoreAdapter): string[] {
  return Object.entries(adapter)
    .filter(([, value]) => typeof value === "function" && value.toString().includes(STUB_MARKER))
    .map(([name]) => name);
}

const stillStubbed = unimplementedMethods(storeAdapter);
if (stillStubbed.length > 0) {
  console.error(
    \`This server's store adapter (src/store.ts) is not yet implemented.\\n\` +
      \`The following method(s) still throw their placeholder error: \${stillStubbed.join(", ")}.\\n\` +
      \`See README.md's "Implement the adapter" section and src/store.ts for exactly what each \` +
      \`method must return, implement them, run "npm run build" again, then restart this server.\\n\` +
      \`(This check only confirms the adapter has been started, not that your implementation is \` +
      \`correct — Adeptra cannot verify that; test each method yourself first, see README.md.)\`,
  );
  process.exit(1);
}

// Adapt StoreAdapter's Cart/CartLineItem shape to mcpTools.ts's
// NormalizedCart/NormalizedLine shape — a thin, direct mapping, since the
// contract was designed to be already close to it.
function toNormalizedCart(cart: Cart) {
  return {
    lines: cart.lineItems.map((li) => ({ id: li.id, productId: li.productId, quantity: li.quantity, title: li.title, price: li.price })),
    currency: cart.currency,
  };
}

const server = new McpServer({ name: "custom-shopping-server", version: "1.0.0" });

registerUcpTools(server, {
  catalog: {
    searchProducts: (query, limit) => storeAdapter.searchProducts(query, limit),
    getProduct: (id) => storeAdapter.getProduct(id),
  },
  cart: {
    getCartRaw: async () => toNormalizedCart(await storeAdapter.getCart()),
    addItem: (productId, quantity) => storeAdapter.addToCart(productId, quantity),
    setItemQty: (lineItemId, quantity) => storeAdapter.updateCartItem(lineItemId, quantity),
    removeItem: (lineItemId) => storeAdapter.removeCartItem(lineItemId),
    emptyCart: () => storeAdapter.emptyCart(),
    checkoutUrl: () => storeAdapter.getCheckoutUrl(),
  },
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("Custom MCP shopping server running (stdio).");
`;
}

function readmeMd(ctx: ArtifactContext): string {
  const label = storeLabel(ctx);
  return `# Custom Store MCP Shopping Server — REFERENCE IMPLEMENTATION

**This is a reference implementation, not a runnable server. You must
implement the store adapter (see \`src/store.ts\`) against your store's own
product and cart layer before it will work.**

Generated by Adeptra Merchant for **${label}**.

## What this is, and isn't

A bespoke store has no standard API Adeptra can generate a working client
for. What this scaffold gives you instead: a correct, complete, boundary-safe,
UCP-shaped MCP shopping server, with the store-specific data access left as
eight clearly-marked integration points in \`src/store.ts\`. \`src/server.ts\`
(the MCP server itself, tool registration, the payment boundary) is complete
— you should not need to touch it. Only \`src/store.ts\` needs work.

## The hard boundary — read this first

**This server is designed to read your catalog and build carts. It must
never take payment — checkout stays on your own store.** Every cart
response's \`continue_url\` comes from your adapter's \`getCheckoutUrl()\`; the
shopper completes the purchase there, through your existing payment setup.
Adeptra generates and configures this server — it does not host it, and it
must never touch your money.

Unlike the WooCommerce and Wix scaffolds, where the boundary is enforced by
which real API endpoints the generated code calls, **here the boundary is a
CONTRACT**: \`src/types.ts\`'s \`StoreAdapter\` interface has no payment method,
no order-creation method, no customer/admin method — that absence is the
entire boundary. This interface intentionally cannot express payment
authorization. **If you find yourself needing to add a payment or
order-creation method to this interface, stop — that is outside this
server's scope**, by design, the same as it is for every other Adeptra-
generated MCP scaffold. Nothing at the type-system level can stop you from
adding one anyway; this is a discipline the interface asks of you, not code
that structurally prevents it.

${ucpConformanceDisclosure()}
## Implement the adapter — what, and in what order

Open \`src/store.ts\`. Every one of its eight methods currently throws an
\`"IMPLEMENT-THIS: ..."\` error explaining exactly what it must return — read
\`src/types.ts\` first, it's the full contract every method implements
against. Recommended order:

1. **\`getProduct\` and \`searchProducts\`** — read-only, the easiest to verify
   against your store directly (see "Test each method" below).
2. **\`getCart\`** — read-only; returning an empty cart (\`lineItems: []\`) for
   "no cart yet" is a valid, expected implementation, not a stub.
3. **\`addToCart\`, \`updateCartItem\`, \`removeCartItem\`, \`emptyCart\`** — the
   cart-mutating group; implement together since they typically share
   cart-lookup logic. \`emptyCart\` must be a REAL, total removal (used to
   guarantee a fresh cart on \`create_cart\` and a genuine cancellation on
   \`cancel_cart\`) — not a session flag.
4. **\`getCheckoutUrl\`** — last, and read its doc comment again before
   writing it: it must return a URL, and must never process payment itself.

## Test each method before running the server

You do not need a running MCP server to test \`src/store.ts\` — it's a plain
object of async functions. After \`npm run build\`:

\`\`\`bash
node --input-type=module -e "
import { storeAdapter } from './dist/store.js';
console.log(await storeAdapter.getProduct('some-real-product-id'));
"
\`\`\`

Swap in a real id/query for each method and confirm the shape matches
\`src/types.ts\` before wiring anything else up. This catches most mistakes
far faster than debugging through the full MCP server.

## What Adeptra can and can't verify here

Because this scaffold can't know your stack, **Adeptra cannot verify your
implementation works against your store.** The startup check in
\`src/server.ts\` only confirms the adapter has been started (none of its
methods still throw the placeholder error) — it is not a correctness check.
Testing each method yourself, as above, is the only way to know it's right.

## Prerequisites

- Node.js 18 or later, on a host you control (a VPS, a small cloud instance,
  a container — anywhere that can run a long-lived Node process). Adeptra
  never hosts this for you.
- A developer comfortable writing a small TypeScript adapter against your
  store's own product/cart data access (a REST API, a database, an SDK —
  whatever your store already has).

## Install

\`\`\`bash
cd mcp-server
npm install
npm run build
\`\`\`

\`npm run build\` succeeds even before you implement \`src/store.ts\` — the
stubs are valid TypeScript that compiles cleanly; they only fail at
*runtime*, deliberately (see the startup check above), not at build time.

## Configure

\`\`\`bash
cp .env.example .env
\`\`\`

Edit \`.env\` and set \`STORE_BASE_URL\` and \`CHECKOUT_URL\` to your real values
— then add whatever else your own \`src/store.ts\` implementation needs (API
keys, tokens, etc.); this scaffold reads nothing else by default.

## Run

\`\`\`bash
npm start
\`\`\`

Until \`src/store.ts\` is implemented, this prints a clear message naming
exactly which adapter methods still need work, and exits — not a stack
trace. Once implemented, this starts the MCP server over stdio, the standard
way MCP clients (agent runtimes, UCP-speaking hosts) launch and talk to a
local MCP server process.

## Connect it to your UCP manifest

Once this server is implemented, deployed, and reachable, point your UCP
manifest's \`dev.ucp.shopping\` service endpoint at its deployed address
(replacing the placeholder Adeptra's manifest fix left there), so agents
that discover your manifest know where to reach this shopping server. The
manifest Adeptra generates for you declares catalog + cart only — never
checkout, since this server doesn't implement it (see "About UCP protocol
conformance" above).

## Prefer not to implement this yourself?

Adeptra also offers a paid setup service that implements this adapter for
you against your store — see your Adeptra dashboard or ask your Adeptra
contact if you'd rather not do this yourself.

## You must complete

- [ ] Implement all eight methods in \`src/store.ts\` against your store —
      this artifact does nothing until you do.
- [ ] Set \`STORE_BASE_URL\` and \`CHECKOUT_URL\` in \`mcp-server/.env\` (plus
      anything else your implementation needs).
- [ ] Deploy this to a host you control (Node 18+) — Adeptra does not host it for you.
- [ ] Point your UCP manifest's shopping service endpoint at this server's
      deployed address, then re-run your Adeptra analysis — that's what turns
      "cart/catalog capability enabled once deployed" into a genuine pass.
- [ ] If your Adeptra checkout-capability signal is failing because checkout
      isn't declared, and you're intentionally using this handoff profile,
      attest to that via the checkout-handoff opt-in in your Adeptra
      dashboard so it scores correctly instead of failing.

## Tools this server exposes

| Tool | Does |
|---|---|
| \`search_catalog\` | Search the catalog by keyword |
| \`lookup_catalog\` | Look up one or more products by id |
| \`get_product\` | Get one product's full details by id |
| \`create_cart\` | Start a new cart session (always empty) |
| \`get_cart\` | Get the current cart contents |
| \`update_cart\` | Replace the cart's full contents (add/change/remove in one call) |
| \`cancel_cart\` | Cancel the cart session (empties it for real) |
`;
}

export function build(ctx: ArtifactContext): ScaffoldProvider {
  const files: ArtifactFile[] = [
    { path: "README.md", contents: readmeMd(ctx) },
    { path: "package.json", contents: packageJson() },
    { path: "tsconfig.json", contents: tsconfigJson() },
    { path: ".env.example", contents: envExample() },
    { path: "src/loadEnv.ts", contents: loadEnvTs() },
    { path: "src/mcpTools.ts", contents: mcpToolsTs() },
    { path: "src/types.ts", contents: typesTs() },
    { path: "src/store.ts", contents: storeTs() },
    { path: "src/server.ts", contents: serverTs() },
  ];

  return {
    files,
    addedLines: [
      "mcp-server/README.md — reference-implementation deploy guide: the not-runnable warning, the payment boundary, the adapter implementation order, and how to test it",
      "mcp-server/package.json — Node project (@modelcontextprotocol/sdk + zod only)",
      "mcp-server/tsconfig.json — build config for `npm run build` (compiles cleanly even before the adapter is implemented)",
      "mcp-server/.env.example — STORE_BASE_URL/CHECKOUT_URL placeholders",
      "mcp-server/src/loadEnv.ts — loads .env before anything else (must be the first import in server.ts)",
      "mcp-server/src/mcpTools.ts — the canonical UCP catalog+cart tool implementation (shared, identical across every Adeptra-generated MCP scaffold)",
      "mcp-server/src/types.ts — the StoreAdapter contract every method in store.ts implements against",
      "mcp-server/src/store.ts — THE INTEGRATION POINT: every method throws IMPLEMENT-THIS until you write it, each with a worked example",
      "mcp-server/src/server.ts — complete MCP server: wires StoreAdapter into UCP's canonical catalog+cart tool set; refuses to start until store.ts is implemented",
    ],
    setupMustComplete: [
      "Implement all eight StoreAdapter methods in mcp-server/src/store.ts against your own store — this artifact does nothing until you do.",
      "Set STORE_BASE_URL and CHECKOUT_URL in mcp-server/.env to your real values (plus anything else your implementation needs).",
    ],
    extraFlagged: [
      "This is a reference implementation, not a working server — every StoreAdapter method throws a placeholder error until a developer implements it against your store.",
      "The payment boundary here is enforced by the StoreAdapter contract (no payment/order/admin method exists to call), which a developer could violate by adding one anyway — the contract says not to, loudly, but nothing at the type level stops it the way WooCommerce's/Wix's real API restrictions do.",
    ],
  };
}
