/**
 * Adeptra Merchant — Wix MCP scaffold provider.
 *
 * CRITICAL DIFFERENCE FROM WOOCOMMERCE: WooCommerce's Store API structurally
 * cannot authorize payment or touch admin data — the safe boundary is
 * enforced by the platform. Wix's eCommerce API CAN create checkouts and
 * orders and its narrowest available OAuth scopes are broader than what this
 * server uses. On Wix, the boundary is enforced by OUR DISCIPLINE, not the
 * platform: this client only ever calls catalog-read and cart-write/current-
 * checkout-redirect endpoints; it never calls order creation or anything
 * that would submit/authorize payment. See src/wix.ts's own header comment
 * (generated below) for the explicit "never call" list, and README.md's
 * "About the permissions you're granting" section for the scope disclosure.
 *
 * All API details (auth flow, cart model, catalog endpoint, checkout
 * handoff) were verified directly against dev.wix.com before writing this,
 * not guessed — see the session's plan message for citations. Two verified
 * facts materially shape this file:
 *   - Catalog V1 vs V3: Wix Stores sites run ONE catalog version, and V1/V3
 *     are not backward-compatible. This scaffold targets V3 only (documented
 *     tradeoff, not a silent gap) — the generated server calls
 *     GetCatalogVersion on startup and exits with a clear message if the
 *     site is on V1, rather than failing confusingly deep in a catalog call.
 *   - The OAuth token endpoint (POST /oauth2/token) is currently marked
 *     "Developer Preview" in Wix's own docs — disclosed in the generated
 *     README and in src/wix.ts's own comment, not hidden.
 */

import type { ArtifactContext, ArtifactFile } from "../types.ts";
import { TARGET_FOLDER, MCP_SDK_VERSION, ZOD_VERSION, storeLabel, tsconfigJson, loadEnvTs, type ScaffoldProvider } from "./shared.ts";

const SITE_URL_PLACEHOLDER = "https://REPLACE-WITH-YOUR-STORE-URL.example";
const CLIENT_ID_PLACEHOLDER = "REPLACE-WITH-YOUR-WIX-OAUTH-CLIENT-ID";

function packageJson(): string {
  return (
    JSON.stringify(
      {
        name: "wix-mcp-shopping-server",
        version: "1.0.0",
        private: true,
        type: "module",
        description: "MCP shopping server for Wix — catalog search + cart building via the Wix eCommerce REST API. Generated by Adeptra Merchant.",
        engines: { node: ">=18" },
        scripts: {
          build: "tsc",
          start: "node dist/server.js",
          dev: "tsc --watch",
        },
        dependencies: {
          "@modelcontextprotocol/sdk": MCP_SDK_VERSION,
          zod: ZOD_VERSION,
        },
        devDependencies: {
          typescript: "^5.7.0",
          "@types/node": "^22.0.0",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function envExample(): string {
  return [
    `WIX_CLIENT_ID=${CLIENT_ID_PLACEHOLDER}`,
    `WIX_SITE_URL=${SITE_URL_PLACEHOLDER}`,
    "",
    "# No client secret — Wix's headless OAuth app flow for visitor/anonymous",
    "# sessions is a public-client flow (Client ID only). See README.md for",
    "# exactly how to create this OAuth app and which permissions to grant —",
    "# read that before deploying; Wix's narrowest available scopes are",
    "# broader than what this server actually uses.",
    "",
  ].join("\n");
}

function wixTs(): string {
  return `/**
 * Thin Wix eCommerce REST client. Catalog reads + cart building + a
 * payment-free checkout handoff ONLY.
 *
 * ENDPOINTS THIS FILE DELIBERATELY NEVER CALLS, AND WHY:
 *   - POST /ecom/v1/orders (Create Order) — creates a real order. Never called.
 *   - Anything that submits or authorizes payment details. Never called, and
 *     never imported/referenced — this file has no payment-related code path
 *     at all. Payment happens exclusively on Wix's own hosted checkout page
 *     (the URL createCheckoutUrl() returns), entered directly by the shopper.
 *   - Any /stores/v3/products WRITE endpoint (create/update/delete products).
 *     Catalog access here is read-only (search + get by id).
 *   - Any orders/customers/analytics/settings read endpoint. This client
 *     reads catalog and the CURRENT VISITOR'S OWN cart only.
 *
 * SCOPE REALITY (see README.md's "About the permissions you're granting"):
 * Wix's narrowest documented scopes for what this server needs are broader
 * than what it actually uses — SCOPE.DC-ECOM-MEGA.MANAGE-ECOM ("Manage
 * eCommerce - all permissions") for cart writes, and
 * SCOPE.DC-STORES.MANAGE-ORDERS ("Manage Orders" — also covers reading
 * orders and creating fulfillments) for checkout creation. There is no
 * narrower option Wix exposes today. This file's own code is the actual
 * boundary: everything above this comment block is the complete list of
 * endpoints it will ever call.
 *
 * AUTH: a visitor access token (Client ID only, no client secret — Wix's
 * public-client flow for anonymous/headless sessions) doubles as the cart's
 * session identity, the same role WooCommerce's Cart-Token header plays —
 * every /ecom/v1/carts/current/* call made with the same token operates on
 * the same visitor's cart, no separate cart id needed. One token per running
 * process, matching the same "one process = one shopper session" assumption
 * the WooCommerce scaffold makes. NOTE: the token endpoint
 * (POST /oauth2/token) is currently marked "Developer Preview" in Wix's own
 * docs as of when this was generated — it may change. Tokens last 4 hours;
 * this client does not implement refresh-token renewal for v1 simplicity —
 * a session longer than that gets a fresh anonymous visitor identity (and
 * empty cart) on its next call, which is very unlikely to matter for a
 * typical MCP session lifetime.
 *
 * CATALOG VERSION: this client targets Wix Catalog V3 only. Wix Stores sites
 * run ONE catalog version (V1 or V3, not backward-compatible), and existing
 * stores may still be on V1. assertCatalogV3() is called on startup by
 * server.ts and exits with a clear message rather than letting a V1 site
 * fail confusingly deep inside a catalog call.
 */

// Read here, but NOT enforced at module load — server.ts's own top-level
// check (before it imports anything that calls these) is what produces the
// clean "set your env vars" message. A throw here at import time would win
// the race against that check every time (imports evaluate before the
// importing module's own body runs) and surface as an ugly uncaught
// exception instead. The check below, inside getAccessToken(), is
// defense-in-depth for anyone importing this file directly.
const CLIENT_ID = process.env.WIX_CLIENT_ID;
const SITE_URL = process.env.WIX_SITE_URL;

const API_BASE = "https://www.wixapis.com";
const STORES_APP_ID = "215238eb-22a5-4c36-9e7b-e7c08025e04e"; // fixed, universal Wix Stores app id — not merchant-specific, safe to hardcode

let accessToken: string | null = null;

async function getAccessToken(): Promise<string> {
  if (accessToken) return accessToken;
  if (!CLIENT_ID || !SITE_URL) {
    throw new Error("Set WIX_CLIENT_ID and WIX_SITE_URL in .env (see .env.example).");
  }
  const res = await fetch(\`\${API_BASE}/oauth2/token\`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ clientId: CLIENT_ID, grantType: "anonymous" }),
  });
  const text = await res.text();
  if (!res.ok) throw new Error(\`Wix OAuth token request -> \${res.status}: \${text}\`);
  const data = JSON.parse(text) as { access_token: string };
  accessToken = data.access_token;
  return accessToken;
}

async function wixFetch(path: string, init: RequestInit = {}): Promise<any> {
  const token = await getAccessToken();
  const headers: Record<string, string> = {
    "content-type": "application/json",
    authorization: \`Bearer \${token}\`,
    ...(init.headers as Record<string, string> | undefined),
  };
  const res = await fetch(\`\${API_BASE}\${path}\`, { ...init, headers });
  const text = await res.text();
  if (!res.ok) {
    throw new Error(\`Wix API \${init.method ?? "GET"} \${path} -> \${res.status}: \${text}\`);
  }
  return text ? JSON.parse(text) : null;
}

/** Throws a clear, actionable error if this site isn't on Catalog V3 — called
 *  once at server startup, before any tool is registered, so the process
 *  fails loudly instead of hitting confusing runtime errors later. A single,
 *  cheap, parameterless call (per Wix's own docs: catalog version is
 *  permanent for a site, one call is sufficient for the whole process).
 *  Throws rather than calling process.exit() itself — exiting immediately
 *  after an in-flight fetch can crash Node on some platforms; main()'s own
 *  catch handler is the one place that sets the exit code, once nothing is
 *  still in flight. */
export async function assertCatalogV3(): Promise<void> {
  const result = await wixFetch("/stores/v3/provision/version");
  const version = result?.catalogVersion;
  if (version === "V3_CATALOG") return;
  if (version === "STORES_NOT_INSTALLED") {
    throw new Error("Wix Stores does not appear to be installed on this site. Install/enable Wix Stores, then retry.");
  }
  throw new Error(
    \`This server requires Wix Catalog V3; your site is on \${version === "V1_CATALOG" ? "Catalog V1" : \`an unrecognized catalog version (\${String(version)})\`}. See README.md's "Known gotcha: Catalog V1 vs V3" for what this means and how to check.\`,
  );
}

export interface Product {
  id: string;
  name: string;
  visible: boolean;
  plainDescription?: string;
}

export async function searchProducts(query: string, limit = 10): Promise<Product[]> {
  const result = await wixFetch("/stores/v3/products/search", {
    method: "POST",
    body: JSON.stringify({
      search: { expression: query, fields: ["name"], fuzzy: true },
      fields: ["DESCRIPTION"],
      cursorPaging: { limit },
    }),
  });
  return result?.products ?? [];
}

export async function getProduct(id: string): Promise<Product> {
  const result = await wixFetch(\`/stores/v3/products/\${id}\`);
  return result?.product;
}

export interface CartLineItem {
  id: string;
  quantity: number;
  catalogReference?: { catalogItemId: string; options?: Record<string, unknown> };
}

export interface Cart {
  id: string;
  lineItems: CartLineItem[];
  currency?: string;
}

export async function getCart(): Promise<Cart> {
  const result = await wixFetch("/ecom/v1/carts/current");
  return result?.cart;
}

/** Wix always requires a variantId, even for a product with no real options
 *  (it gets one "default variant") — call get_product first to find it in
 *  the product's variantsInfo.variants. */
export async function addToCart(productId: string, variantId: string, quantity: number): Promise<Cart> {
  const result = await wixFetch("/ecom/v1/carts/current/add-to-cart", {
    method: "POST",
    body: JSON.stringify({
      lineItems: [
        {
          catalogReference: { appId: STORES_APP_ID, catalogItemId: productId, options: { variantId } },
          quantity,
        },
      ],
    }),
  });
  return result?.cart;
}

export async function updateCartItem(lineItemId: string, quantity: number): Promise<Cart> {
  const result = await wixFetch("/ecom/v1/carts/current/update-line-items-quantity", {
    method: "POST",
    body: JSON.stringify({ lineItems: [{ id: lineItemId, quantity }] }),
  });
  return result?.cart;
}

export async function removeCartItem(lineItemId: string): Promise<Cart> {
  const result = await wixFetch("/ecom/v1/carts/current/remove-line-items", {
    method: "POST",
    body: JSON.stringify({ lineItemIds: [lineItemId] }),
  });
  return result?.cart;
}

/** Two Wix API calls, not one: create a checkout object from the current
 *  cart (returns only a checkoutId, no URL), then create a redirect session
 *  for that checkout (returns the actual URL). Neither call authorizes or
 *  completes payment — createCheckoutFromCurrentCart creates a pre-payment
 *  checkout object, and the redirect session's URL points to Wix's own
 *  hosted checkout page where the SHOPPER enters payment directly with Wix. */
export async function createCheckoutUrl(): Promise<string> {
  const checkoutResult = await wixFetch("/ecom/v1/carts/current/create-checkout", {
    method: "POST",
    body: JSON.stringify({ channelType: "WEB" }),
  });
  const checkoutId = checkoutResult?.checkoutId;
  if (!checkoutId) throw new Error("Wix did not return a checkoutId from create-checkout.");

  const redirectResult = await wixFetch("/redirect-session/v1/redirect-session", {
    method: "POST",
    body: JSON.stringify({
      ecomCheckout: { checkoutId },
      callbacks: { postFlowUrl: SITE_URL },
    }),
  });
  const fullUrl = redirectResult?.redirectSession?.fullUrl;
  if (!fullUrl) throw new Error("Wix did not return a redirect URL from create-redirect-session.");
  return fullUrl;
}
`;
}

function serverTs(): string {
  return `/**
 * Adeptra Merchant — Wix MCP Shopping Server.
 *
 * Makes this store's catalog searchable and its cart buildable by an MCP-
 * speaking AI shopping agent. HARD BOUNDARY: this server never processes
 * payment. begin_checkout returns the current cart plus a Wix-hosted
 * checkout URL — the agent/shopper hands off to Wix's own checkout from
 * there to complete payment. See wix.ts's header comment for the explicit
 * list of endpoints this server deliberately never calls.
 */

import "./loadEnv.js"; // MUST be the first import — see loadEnv.ts's header

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { assertCatalogV3, searchProducts, getProduct, getCart, addToCart, updateCartItem, removeCartItem, createCheckoutUrl } from "./wix.js";

if (!process.env.WIX_CLIENT_ID || !process.env.WIX_SITE_URL) {
  console.error("Set WIX_CLIENT_ID and WIX_SITE_URL in .env (see .env.example) before starting this server.");
  process.exit(1);
}

const server = new McpServer({ name: "wix-shopping-server", version: "1.0.0" });

function textResult(data: unknown) {
  return { content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }] };
}

server.registerTool(
  "search_products",
  {
    title: "Search products",
    description: "Search this store's product catalog by keyword.",
    inputSchema: {
      query: z.string().describe("Search text, e.g. product name or keyword"),
      limit: z.number().int().min(1).max(50).optional(),
    },
  },
  async ({ query, limit }) => textResult(await searchProducts(query, limit ?? 10)),
);

server.registerTool(
  "get_product",
  {
    title: "Get product",
    description: "Get full details for one product by its id, including its variants (needed for add_to_cart).",
    inputSchema: { id: z.string().describe("Product id, from search_products output") },
  },
  async ({ id }) => textResult(await getProduct(id)),
);

server.registerTool(
  "add_to_cart",
  {
    title: "Add to cart",
    description:
      "Add a product to the shopping cart. Wix requires a variantId even for products with no real options (they have one default variant) — call get_product first and read it from the product's variantsInfo.variants.",
    inputSchema: {
      productId: z.string().describe("Product id, from search_products/get_product output"),
      variantId: z.string().describe("Variant id, from get_product's variantsInfo.variants"),
      quantity: z.number().int().min(1).default(1),
    },
  },
  async ({ productId, variantId, quantity }) => textResult(await addToCart(productId, variantId, quantity)),
);

server.registerTool(
  "update_cart_item",
  {
    title: "Update cart item",
    description: "Change the quantity of an existing cart line item.",
    inputSchema: {
      lineItemId: z.string().describe("The cart line item's id, from get_cart/add_to_cart output"),
      quantity: z.number().int().min(1),
    },
  },
  async ({ lineItemId, quantity }) => textResult(await updateCartItem(lineItemId, quantity)),
);

server.registerTool(
  "remove_cart_item",
  {
    title: "Remove cart item",
    description: "Remove a line item from the cart.",
    inputSchema: { lineItemId: z.string().describe("The cart line item's id, from get_cart/add_to_cart output") },
  },
  async ({ lineItemId }) => textResult(await removeCartItem(lineItemId)),
);

server.registerTool(
  "get_cart",
  {
    title: "Get cart",
    description: "Get the current cart contents.",
    inputSchema: {},
  },
  async () => textResult(await getCart()),
);

server.registerTool(
  "begin_checkout",
  {
    title: "Begin checkout",
    description:
      "Returns the current cart summary and a Wix-hosted checkout URL. Does NOT process payment — hand off to checkout_url for the shopper to complete their purchase directly with Wix.",
    inputSchema: {},
  },
  async () => {
    const cart = await getCart();
    const checkout_url = await createCheckoutUrl();
    return textResult({
      cart,
      checkout_url,
      note: "Payment is not handled by this server — complete the purchase at checkout_url, on Wix's own hosted checkout page.",
    });
  },
);

async function main() {
  await assertCatalogV3(); // hard-fails with a clear message if this site isn't on Catalog V3 — see wix.ts
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("Wix MCP shopping server running (stdio).");
}

main().catch((e) => {
  console.error(\`Failed to start: \${(e as Error).message ?? e}\`);
  // process.exitCode, not process.exit() — calling exit() immediately after
  // an in-flight fetch (assertCatalogV3, above) can crash Node on some
  // platforms; setting the code and letting the event loop drain naturally
  // avoids that while still exiting non-zero.
  process.exitCode = 1;
});
`;
}

function readmeMd(ctx: ArtifactContext): string {
  const label = storeLabel(ctx);
  return `# Wix MCP Shopping Server

**This server is for Wix stores. If your store is not on Wix, do not deploy this.**

Generated by Adeptra Merchant for **${label}**.

## What this is

An MCP (Model Context Protocol) server that lets an AI shopping agent search
this store's product catalog and build a cart, using Wix's eCommerce REST
API. Its tools follow the same catalog/cart vocabulary your UCP manifest
declares.

## The hard boundary — read this first

**This server reads your catalog and builds carts. It never takes payment —
checkout stays on Wix.** The \`begin_checkout\` tool returns the current cart
plus a Wix-hosted checkout URL; the shopper (or the agent, on the shopper's
behalf) completes the purchase there, directly with Wix, through your
existing payment setup. Adeptra generated and configured this server — it
does not host it, and it never touches your money.

## About the permissions you're granting — read this before creating the OAuth app

Unlike a WooCommerce store (where the equivalent API is structurally
incapable of touching payment or admin data, no matter what), **Wix does not
currently offer a narrower permission scope than the ones below** — granting
this app the minimum scopes it needs still grants more than it uses:

| Scope | What Wix calls it | What this server actually uses it for |
|---|---|---|
| \`SCOPE.STORES.PRODUCT_READ\` | Read Stores products | Searching/reading your product catalog (read-only) |
| \`SCOPE.STORES.CATALOG_READ_LIMITED\` | Read v3 catalog | The one-time startup check confirming your site is on Catalog V3 |
| \`SCOPE.DC-ECOM-MEGA.MANAGE-ECOM\` | Manage eCommerce - all permissions | Building/reading the current visitor's own cart, ONLY |
| \`SCOPE.DC-STORES.MANAGE-ORDERS\` | Manage Orders | Creating a checkout object and its redirect URL, ONLY — this scope also nominally allows reading orders and creating fulfillments, which this server's code never does |

This server's code is the actual boundary: \`src/wix.ts\`'s header comment
lists every endpoint it calls, and explicitly, every endpoint it deliberately
never calls (order creation, payment submission, any catalog write, any
customer/order/settings read). Nothing in this codebase imports or
references a payment API. But because the grant itself is broader than the
usage, **treat your deployed server and its \`WIX_CLIENT_ID\` as sensitive** —
host it the way you'd host anything with elevated store access, not as a
disposable public script.

## Known gotcha: the Wix OAuth token endpoint is a Developer Preview API

The endpoint this server uses to get a visitor access token
(\`POST /oauth2/token\`) is currently marked "Developer Preview" in Wix's own
documentation, meaning Wix may change it. This is disclosed here, not hidden
— if authentication starts failing after a Wix platform update, this is the
first place to check.

## Prerequisites

- Node.js 18 or later, on a host you control (a VPS, a small cloud instance,
  a container — anywhere that can run a long-lived Node process). Adeptra
  never hosts this for you.
- A Wix site with Wix Stores enabled, on Catalog V3 (see the gotcha below).

## Wix setup, step by step

1. **Create a Headless project.** In your Wix account, go to your site's
   dashboard and set up a Headless project (Wix's "Headless Settings" area —
   see [dev.wix.com/docs/go-headless](https://dev.wix.com/docs/go-headless)
   for the current path, since dashboard navigation can change).
2. **Make sure Wix Stores/eCommerce is enabled** on the site this project
   points at. If you're not sure, check your site's dashboard for the Stores
   app.
3. **Create an OAuth app for visitors.** Within your Headless project
   settings, create a new OAuth app scoped for visitor (anonymous shopper)
   access — Wix's docs title this flow "Create an OAuth App for Visitors and
   Members." We're not naming exact buttons here because dashboard wording
   changes; look for the OAuth app creation option in your Headless project
   settings.
4. **Grant ONLY the four permissions listed in the table above.** Do not
   grant anything related to customer data, site settings, billing, or
   marketing — this server needs none of it and never asks for it.
5. **Set the allowed domain** for the OAuth app to wherever you deploy this
   server (or leave it permissive during local testing, per your Headless
   project's own domain-restriction settings).
6. **Copy the Client ID** (Wix's docs also call this the "Client GUID") from
   your OAuth app's settings — you'll need it for \`.env\` below.

## Install

\`\`\`bash
cd mcp-server
npm install
npm run build
\`\`\`

## Configure

\`\`\`bash
cp .env.example .env
\`\`\`

Edit \`.env\` and set \`WIX_CLIENT_ID\` (from step 6 above) and \`WIX_SITE_URL\`
to your real store URL. No client secret is needed or used — Wix's headless
OAuth flow for anonymous visitor sessions is a public-client flow (Client ID
only).

## Run

\`\`\`bash
npm start
\`\`\`

This starts the MCP server over stdio — the standard way MCP clients (agent
runtimes, UCP-speaking hosts) launch and talk to a local MCP server process.
On startup, it checks your site's catalog version first and exits with a
clear error if your site isn't on Catalog V3 (see the gotcha below) — it
will not fail confusingly deep inside a catalog call.

## Connect it to your UCP manifest

Once this server is deployed somewhere reachable, point your UCP manifest's
\`dev.ucp.shopping\` service endpoint at its deployed address (replacing the
placeholder Adeptra's manifest fix left there), so agents that discover your
manifest know where to reach this shopping server.

## Known gotcha: Catalog V1 vs V3

Wix Stores sites run on one of two catalog versions, V1 or V3, which are
**not** backward-compatible — and Wix has been migrating sites to V3
gradually (new sites first), so your site may still be on V1. This server
only supports Catalog V3 and checks for it automatically on startup, exiting
with a clear message ("This server requires Wix Catalog V3; your site is on
Catalog V1.") if your site isn't ready. If you hit that message: this isn't
something you can toggle yourself today — check with Wix support about your
site's catalog migration status, or contact Adeptra if you need V1 support
prioritized.

## Known gotcha: pre-headless stores may not expose all product fields

Stores created before Wix's headless features were enabled may not expose
every product field via the API without enabling specific site capabilities
first. If \`search_products\`/\`get_product\` return unexpectedly sparse data,
check your site's Headless project settings for any catalog-related
capability that needs enabling, and re-test with \`curl\` directly against
the Wix API using your access token before assuming this server is broken.

## You must complete

- [ ] Create the Wix Headless project + OAuth app (see "Wix setup" above).
- [ ] Grant only the minimum permissions listed above — no more.
- [ ] Set \`WIX_CLIENT_ID\` and \`WIX_SITE_URL\` in \`mcp-server/.env\`.
- [ ] Deploy this to a host you control (Node 18+) — Adeptra does not host it for you.
- [ ] Verify your site is on Catalog V3 and that product fields are exposed via the API (see the gotchas above) — the server's own startup check catches the catalog-version half of this for you.
- [ ] Point your UCP manifest's shopping service endpoint at this server's
      deployed address, then re-run your Adeptra analysis — that's what turns
      "cart/catalog/checkout capability enabled once deployed" into a genuine pass.

## Tools this server exposes

| Tool | Does |
|---|---|
| \`search_products\` | Search the catalog by keyword |
| \`get_product\` | Get one product's full details + variants by id |
| \`add_to_cart\` | Add a product (+ variant) to the cart |
| \`update_cart_item\` | Change a cart line item's quantity |
| \`remove_cart_item\` | Remove a cart line item |
| \`get_cart\` | Get current cart contents |
| \`begin_checkout\` | Return the cart + a Wix-hosted checkout URL (no payment) |
`;
}

export function build(ctx: ArtifactContext): ScaffoldProvider {
  const files: ArtifactFile[] = [
    { path: "README.md", contents: readmeMd(ctx) },
    { path: "package.json", contents: packageJson() },
    { path: "tsconfig.json", contents: tsconfigJson() },
    { path: ".env.example", contents: envExample() },
    { path: "src/loadEnv.ts", contents: loadEnvTs() },
    { path: "src/server.ts", contents: serverTs() },
    { path: "src/wix.ts", contents: wixTs() },
  ];

  return {
    files,
    addedLines: [
      "mcp-server/README.md — deploy guide, the payment boundary, the OAuth setup walkthrough, and the scope disclosure, in plain English",
      "mcp-server/package.json — Node project (@modelcontextprotocol/sdk + zod only — raw REST, no Wix SDK)",
      "mcp-server/tsconfig.json — build config for `npm run build`",
      "mcp-server/.env.example — WIX_CLIENT_ID/WIX_SITE_URL placeholders (no client secret needed)",
      "mcp-server/src/loadEnv.ts — loads .env before anything else (must be the first import in server.ts)",
      "mcp-server/src/server.ts — MCP tools: search_products, get_product, add_to_cart, update_cart_item, remove_cart_item, get_cart, begin_checkout; checks Catalog V3 on startup",
      "mcp-server/src/wix.ts — Wix eCommerce REST client (catalog read + cart write + checkout redirect only; explicit never-call list in its own header comment)",
    ],
    setupMustComplete: [
      "Create the Wix Headless project + OAuth app for visitors, and grant ONLY the minimum permissions listed in the README's scope table.",
      "Set WIX_CLIENT_ID and WIX_SITE_URL in mcp-server/.env to your real values.",
      "Verify your site is on Wix Catalog V3 (the server's startup check catches this) and that product fields are exposed via the API — see the README's known gotchas.",
    ],
    extraFlagged: [
      "Wix's narrowest available OAuth scopes for this server's needs are broader than what it actually uses (see README.md's scope table) — this server's own code, not the platform, is what keeps it from touching payment, orders, or admin data.",
      "The Wix OAuth token endpoint this server depends on is currently marked Developer Preview by Wix and may change.",
    ],
  };
}
