/**
 * Adeptra Merchant — WooCommerce MCP scaffold provider.
 *
 * THE SAFE BOUNDARY IS ENFORCED BY API CHOICE, NOT JUST CONVENTION: every
 * generated call goes through WooCommerce's public, unauthenticated Store API
 * (/wp-json/wc/store/v1/*) for catalog reads and cart building ONLY. Nothing
 * generated here ever calls /wc/store/v1/checkout (payment) or any /wc/v3/
 * (admin — orders/customers/settings) route. The cart's continue_url hands
 * off to the store's own checkout page; nothing here processes payment. This
 * boundary is asserted by a dedicated test (see test_artifacts.ts).
 *
 * CANONICAL UCP TOOL SURFACE: search_catalog, lookup_catalog, get_product,
 * create_cart, get_cart, update_cart, cancel_cart — implemented generically
 * in scaffold/shared.ts's mcpToolsTs() (session state machine, diff-and-
 * reconcile, continue_url caching, the not_found business-outcome shape).
 * This file supplies only WooCommerce's own primitives (catalog reads, cart
 * writes) with results normalized to the shape shared/mcpTools.ts expects.
 *
 * LATENT BUG FOUND AND FIXED DURING THIS REWRITE: the original scaffold's
 * woocommerce.ts threw at module load if WOOCOMMERCE_STORE_URL was unset —
 * the exact class of import-order bug found and fixed for Wix (ES modules
 * evaluate all static imports before the importing module's own top-level
 * code runs, so this file's own throw always won the race against
 * server.ts's friendlier check, surfacing an uncaught-exception stack trace
 * instead of a clean message). Never actually re-tested with a truly empty
 * .env after the loadEnv.ts fix, so it shipped unnoticed. Fixed here the
 * same way as Wix: no module-level throw, a lazy assertion function called
 * at point of use instead.
 */

import type { ArtifactContext, ArtifactFile } from "../types.ts";
import {
  TARGET_FOLDER,
  MCP_SDK_VERSION,
  ZOD_VERSION,
  storeLabel,
  tsconfigJson,
  loadEnvTs,
  mcpToolsTs,
  ucpConformanceDisclosure,
  type ScaffoldProvider,
} from "./shared.ts";

const STORE_URL_PLACEHOLDER = "https://REPLACE-WITH-YOUR-STORE-URL.example";

function packageJson(): string {
  return (
    JSON.stringify(
      {
        name: "woocommerce-mcp-shopping-server",
        version: "1.0.0",
        private: true,
        type: "module",
        description: "MCP shopping server for WooCommerce — UCP catalog + cart, via the WooCommerce Store API. Generated by Adeptra Merchant.",
        engines: { node: ">=18" },
        scripts: {
          build: "tsc",
          start: "node dist/server.js",
          dev: "tsc --watch",
        },
        dependencies: {
          "@modelcontextprotocol/sdk": MCP_SDK_VERSION,
          zod: ZOD_VERSION,
        },
        devDependencies: {
          typescript: "^5.7.0",
          "@types/node": "^22.0.0",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function envExample(): string {
  return [
    `WOOCOMMERCE_STORE_URL=${STORE_URL_PLACEHOLDER}`,
    "",
    "# The WooCommerce Store API's catalog and cart endpoints are public/",
    "# unauthenticated by design — no API key or secret is required or used here.",
    "# That's also why this server structurally cannot touch payment or admin",
    "# data: it was never given credentials that could reach those endpoints.",
    "",
    "# Optional — override only if your store's checkout page isn't at the",
    "# WooCommerce default path.",
    "WOOCOMMERCE_CHECKOUT_PATH=/checkout/",
    "",
  ].join("\n");
}

function woocommerceTs(): string {
  return `/**
 * Thin WooCommerce Store API client. Catalog reads + cart building ONLY —
 * this file never calls /wc/store/v1/checkout (payment) or any /wc/v3/
 * (admin) route. Exports the primitive functions registerUcpTools (see
 * mcpTools.ts) wires up as this platform's CatalogPrimitives/CartPrimitives
 * — every function here returns NORMALIZED shapes (NormalizedProduct /
 * NormalizedCart), not WooCommerce's own raw REST response shape.
 *
 * Cart state persists across calls via the Cart-Token header (the documented
 * headless pattern): the first cart-touching request returns a Cart-Token
 * response header, cached here in memory and replayed on every subsequent
 * call. When using Cart-Token, no separate nonce is required.
 *
 * One in-memory cart token per running process — this scaffold assumes one
 * server process serves one shopper session at a time (the typical MCP
 * stdio deployment model: one process per connected agent session). A
 * multi-shopper deployment would need a per-session token store instead.
 */

import type { NormalizedProduct, NormalizedCart } from "./mcpTools.js";

const STORE_URL = process.env.WOOCOMMERCE_STORE_URL;
const CHECKOUT_PATH = process.env.WOOCOMMERCE_CHECKOUT_PATH || "/checkout/";

// NOT enforced at module load — server.ts's own top-level check (before it
// imports anything that calls these) is what produces the clean "set your
// env vars" message. A throw here at import time would win the race
// against that check every time (imports evaluate before the importing
// module's own body runs) and surface as an ugly uncaught exception
// instead. assertStoreUrl(), called at the point of use, is defense-in-
// depth for anyone importing this file directly.
function assertStoreUrl(): string {
  if (!STORE_URL) throw new Error("Set WOOCOMMERCE_STORE_URL in .env (see .env.example).");
  return STORE_URL;
}

let cartToken: string | null = null;

async function storeApiFetch(path: string, init: RequestInit = {}): Promise<any> {
  const base = \`\${assertStoreUrl().replace(/\\/+$/, "")}/wp-json/wc/store/v1\`;
  const headers: Record<string, string> = {
    "content-type": "application/json",
    ...(init.headers as Record<string, string> | undefined),
  };
  if (cartToken) headers["Cart-Token"] = cartToken;

  const res = await fetch(\`\${base}\${path}\`, { ...init, headers });
  const token = res.headers.get("Cart-Token");
  if (token) cartToken = token;

  const text = await res.text();
  if (!res.ok) {
    throw new Error(\`WooCommerce Store API \${init.method ?? "GET"} \${path} -> \${res.status}: \${text}\`);
  }
  return text ? JSON.parse(text) : null;
}

interface RawProduct {
  id: number;
  name: string;
  permalink: string;
  prices: { price: string; currency_code: string };
}

function toNormalizedProduct(p: RawProduct): NormalizedProduct {
  return { id: String(p.id), title: p.name, price: p.prices?.price, currency: p.prices?.currency_code, url: p.permalink };
}

export async function searchProducts(query: string, limit: number): Promise<NormalizedProduct[]> {
  const q = new URLSearchParams({ search: query, per_page: String(limit) });
  const raw: RawProduct[] = await storeApiFetch(\`/products?\${q.toString()}\`);
  return raw.map(toNormalizedProduct);
}

export async function getProduct(id: string): Promise<NormalizedProduct> {
  const raw: RawProduct = await storeApiFetch(\`/products/\${id}\`);
  return toNormalizedProduct(raw);
}

interface RawCartItem {
  key: string;
  id: number;
  name: string;
  quantity: number;
  prices: { price: string };
}

interface RawCart {
  items: RawCartItem[];
}

function toNormalizedCart(raw: RawCart): NormalizedCart {
  return {
    lines: raw.items.map((i) => ({ id: i.key, productId: String(i.id), quantity: i.quantity, title: i.name, price: i.prices?.price })),
  };
}

export async function getCartRaw(): Promise<NormalizedCart> {
  const raw: RawCart = await storeApiFetch("/cart");
  return toNormalizedCart(raw);
}

export async function addItem(productId: string, quantity: number): Promise<void> {
  await storeApiFetch("/cart/add-item", { method: "POST", body: JSON.stringify({ id: Number(productId), quantity }) });
}

export async function setItemQty(lineItemId: string, quantity: number): Promise<void> {
  await storeApiFetch("/cart/update-item", { method: "POST", body: JSON.stringify({ key: lineItemId, quantity }) });
}

export async function removeItem(lineItemId: string): Promise<void> {
  await storeApiFetch("/cart/remove-item", { method: "POST", body: JSON.stringify({ key: lineItemId }) });
}

/** No bulk-clear endpoint is used here — built from the already-verified
 *  single-item removeItem() instead of assuming an unverified bulk-clear
 *  route exists on every WooCommerce Store API installation. */
export async function emptyCart(): Promise<void> {
  const cart = await getCartRaw();
  for (const line of cart.lines) {
    await removeItem(line.id);
  }
}

/** A static computed URL — no API call needed, this platform's checkout
 *  page is always at a known path. */
export async function checkoutUrl(): Promise<string> {
  return \`\${assertStoreUrl().replace(/\\/+$/, "")}\${CHECKOUT_PATH}\`;
}
`;
}

function serverTs(): string {
  return `/**
 * Adeptra Merchant — WooCommerce MCP Shopping Server.
 *
 * Implements UCP's canonical catalog + cart tool surface (search_catalog,
 * lookup_catalog, get_product, create_cart, get_cart, update_cart,
 * cancel_cart — see mcpTools.ts) against WooCommerce's Store API. HARD
 * BOUNDARY: this server never processes payment. The cart's continue_url
 * hands off to this store's own checkout page — no /wc/store/v1/checkout
 * call, no /wc/v3/ (admin) call, anywhere in this file or woocommerce.ts.
 * See README.md's "About UCP protocol conformance" section for exactly
 * what is and isn't UCP-conformant here.
 */

import "./loadEnv.js"; // MUST be the first import — see loadEnv.ts's header

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { registerUcpTools } from "./mcpTools.js";
import { searchProducts, getProduct, getCartRaw, addItem, setItemQty, removeItem, emptyCart, checkoutUrl } from "./woocommerce.js";

if (!process.env.WOOCOMMERCE_STORE_URL) {
  console.error("Set WOOCOMMERCE_STORE_URL in .env (see .env.example) before starting this server.");
  process.exit(1);
}

const server = new McpServer({ name: "woocommerce-shopping-server", version: "1.0.0" });

registerUcpTools(server, {
  catalog: { searchProducts, getProduct },
  cart: { getCartRaw, addItem, setItemQty, removeItem, emptyCart, checkoutUrl },
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("WooCommerce MCP shopping server running (stdio).");
`;
}

function readmeMd(ctx: ArtifactContext): string {
  const label = storeLabel(ctx);
  return `# WooCommerce MCP Shopping Server

Generated by Adeptra Merchant for **${label}**.

## What this is

An MCP (Model Context Protocol) server that implements UCP's catalog and
cart shopping capabilities, letting an AI shopping agent search this store's
product catalog and build a cart, using WooCommerce's built-in Store API.

## The hard boundary — read this first

**This server reads your catalog and builds carts. It never takes payment —
checkout stays on your store.** Nothing in this server calls WooCommerce's
checkout/payment endpoints or exposes admin data. Every cart response
includes a \`continue_url\` pointing at your store's normal checkout page; the
shopper (or the agent, on the shopper's behalf) completes the purchase
there, through your existing payment setup. Adeptra generated and
configured this server — it does not host it, and it never touches your
money.

${ucpConformanceDisclosure()}
## Prerequisites

- Node.js 18 or later, on a host you control (a VPS, a small cloud instance,
  a container — anywhere that can run a long-lived Node process). Adeptra
  never hosts this for you.
- Your store must expose the WooCommerce Store API (standard on modern
  WooCommerce/WooCommerce Blocks). Verify with:
  \`curl https://yourstore.example.com/wp-json/wc/store/v1/products\`
  You should get back a JSON array, not a 404 or a login page.

## Install

\`\`\`bash
cd mcp-server
npm install
npm run build
\`\`\`

## Configure

\`\`\`bash
cp .env.example .env
\`\`\`

Edit \`.env\` and set \`WOOCOMMERCE_STORE_URL\` to your real store URL. No API
key or secret is required — the Store API's catalog and cart endpoints are
public/unauthenticated by design (that's also why this server can't touch
payment or admin data: it was never given the keys to).

## Run

\`\`\`bash
npm start
\`\`\`

This starts the MCP server over stdio — the standard way MCP clients (agent
runtimes, UCP-speaking hosts) launch and talk to a local MCP server process.

## Connect it to your UCP manifest

Once this server is deployed somewhere reachable, point your UCP manifest's
\`dev.ucp.shopping\` service endpoint at its deployed address (replacing the
placeholder Adeptra's manifest fix left there), so agents that discover your
manifest know where to reach this shopping server. The manifest Adeptra
generates for you declares catalog + cart only — never checkout, since this
server doesn't implement it (see "About UCP protocol conformance" above).

## You must complete

- [ ] Deploy this to a host you control — Adeptra does not host it for you.
- [ ] Set the real \`WOOCOMMERCE_STORE_URL\` in \`.env\`.
- [ ] Confirm the Store API responds (see Prerequisites above).
- [ ] Point your UCP manifest's shopping service endpoint at this server's
      deployed address, then re-run your Adeptra analysis — that's what turns
      "cart/catalog capability enabled once deployed" into a genuine pass.
- [ ] If your Adeptra checkout-capability signal is failing because checkout
      isn't declared, and you're intentionally using this handoff profile,
      attest to that via the checkout-handoff opt-in in your Adeptra
      dashboard so it scores correctly instead of failing.

## Tools this server exposes

| Tool | Does |
|---|---|
| \`search_catalog\` | Search the catalog by keyword |
| \`lookup_catalog\` | Look up one or more products by id |
| \`get_product\` | Get one product's full details by id |
| \`create_cart\` | Start a new cart session (always empty) |
| \`get_cart\` | Get the current cart contents |
| \`update_cart\` | Replace the cart's full contents (add/change/remove in one call) |
| \`cancel_cart\` | Cancel the cart session (empties it for real) |
`;
}

export function build(ctx: ArtifactContext): ScaffoldProvider {
  const files: ArtifactFile[] = [
    { path: "README.md", contents: readmeMd(ctx) },
    { path: "package.json", contents: packageJson() },
    { path: "tsconfig.json", contents: tsconfigJson() },
    { path: ".env.example", contents: envExample() },
    { path: "src/loadEnv.ts", contents: loadEnvTs() },
    { path: "src/mcpTools.ts", contents: mcpToolsTs() },
    { path: "src/server.ts", contents: serverTs() },
    { path: "src/woocommerce.ts", contents: woocommerceTs() },
  ];

  return {
    files,
    addedLines: [
      "mcp-server/README.md — deploy guide and the payment boundary, in plain English",
      "mcp-server/package.json — Node project (@modelcontextprotocol/sdk + zod only)",
      "mcp-server/tsconfig.json — build config for `npm run build`",
      "mcp-server/.env.example — WOOCOMMERCE_STORE_URL placeholder (no API key needed)",
      "mcp-server/src/loadEnv.ts — loads .env before anything else (must be the first import in server.ts)",
      "mcp-server/src/mcpTools.ts — the canonical UCP catalog+cart tool implementation (shared, identical across every Adeptra-generated MCP scaffold)",
      "mcp-server/src/server.ts — wires WooCommerce's primitives into the shared UCP tool set",
      "mcp-server/src/woocommerce.ts — WooCommerce Store API client (catalog + cart only; no payment, no admin API)",
    ],
    setupMustComplete: [
      "Set WOOCOMMERCE_STORE_URL in mcp-server/.env to your real store URL.",
      "Confirm your store exposes the WooCommerce Store API (GET /wp-json/wc/store/v1/products should return JSON) — standard on modern WooCommerce, but verify since some hosts/security plugins block wp-json routes.",
    ],
    extraFlagged: [],
  };
}
