/**
 * Adeptra Merchant — WooCommerce MCP scaffold provider.
 *
 * THE SAFE BOUNDARY IS ENFORCED BY API CHOICE, NOT JUST CONVENTION: every
 * generated call goes through WooCommerce's public, unauthenticated Store API
 * (/wp-json/wc/store/v1/*) for catalog reads and cart building ONLY. Nothing
 * generated here ever calls /wc/store/v1/checkout (payment) or any /wc/v3/
 * (admin — orders/customers/settings) route. begin_checkout returns the cart
 * summary + the store's own checkout URL for handoff; it does not process
 * payment. This boundary is asserted by a dedicated test (see test_artifacts.ts).
 *
 * Extracted unchanged from the original single-file mcpScaffoldArtifact.ts —
 * output is byte-identical (see test_artifacts.ts's golden-fixture regression
 * test) — as part of generalizing the generator to dispatch per ctx.platform.
 */

import type { ArtifactContext, ArtifactFile } from "../types.ts";
import {
  TARGET_FOLDER,
  MCP_SDK_VERSION,
  ZOD_VERSION,
  storeLabel,
  tsconfigJson,
  loadEnvTs,
  TOOL_ANNOTATIONS_NOTE,
  ucpConformanceDisclosure,
  type ScaffoldProvider,
} from "./shared.ts";

const STORE_URL_PLACEHOLDER = "https://REPLACE-WITH-YOUR-STORE-URL.example";

function packageJson(): string {
  return (
    JSON.stringify(
      {
        name: "woocommerce-mcp-shopping-server",
        version: "1.0.0",
        private: true,
        type: "module",
        description: "MCP shopping server for WooCommerce — catalog search + cart building via the WooCommerce Store API. Generated by Adeptra Merchant.",
        engines: { node: ">=18" },
        scripts: {
          build: "tsc",
          start: "node dist/server.js",
          dev: "tsc --watch",
        },
        dependencies: {
          "@modelcontextprotocol/sdk": MCP_SDK_VERSION,
          zod: ZOD_VERSION,
        },
        devDependencies: {
          typescript: "^5.7.0",
          "@types/node": "^22.0.0",
        },
      },
      null,
      2,
    ) + "\n"
  );
}

function envExample(): string {
  return [
    `WOOCOMMERCE_STORE_URL=${STORE_URL_PLACEHOLDER}`,
    "",
    "# The WooCommerce Store API's catalog and cart endpoints are public/",
    "# unauthenticated by design — no API key or secret is required or used here.",
    "# That's also why this server structurally cannot touch payment or admin",
    "# data: it was never given credentials that could reach those endpoints.",
    "",
    "# Optional — override only if your store's checkout page isn't at the",
    "# WooCommerce default path.",
    "WOOCOMMERCE_CHECKOUT_PATH=/checkout/",
    "",
  ].join("\n");
}

function woocommerceTs(): string {
  return `/**
 * Thin WooCommerce Store API client. Catalog reads + cart building ONLY —
 * this file never calls /wc/store/v1/checkout (payment) or any /wc/v3/
 * (admin) route.
 *
 * Cart state persists across calls via the Cart-Token header (the documented
 * headless pattern): the first cart-touching request returns a Cart-Token
 * response header, cached here in memory and replayed on every subsequent
 * call. When using Cart-Token, no separate nonce is required.
 *
 * One in-memory cart token per running process — this scaffold assumes one
 * server process serves one shopper session at a time (the typical MCP
 * stdio deployment model: one process per connected agent session). A
 * multi-shopper deployment would need a per-session token store instead.
 */

const STORE_URL = process.env.WOOCOMMERCE_STORE_URL;
if (!STORE_URL) {
  throw new Error("Set WOOCOMMERCE_STORE_URL in .env (see .env.example).");
}

const BASE = \`\${STORE_URL.replace(/\\/+$/, "")}/wp-json/wc/store/v1\`;

let cartToken: string | null = null;

async function storeApiFetch(path: string, init: RequestInit = {}): Promise<any> {
  const headers: Record<string, string> = {
    "content-type": "application/json",
    ...(init.headers as Record<string, string> | undefined),
  };
  if (cartToken) headers["Cart-Token"] = cartToken;

  const res = await fetch(\`\${BASE}\${path}\`, { ...init, headers });
  const token = res.headers.get("Cart-Token");
  if (token) cartToken = token;

  const text = await res.text();
  if (!res.ok) {
    throw new Error(\`WooCommerce Store API \${init.method ?? "GET"} \${path} -> \${res.status}: \${text}\`);
  }
  return text ? JSON.parse(text) : null;
}

export interface Product {
  id: number;
  name: string;
  sku: string;
  permalink: string;
  short_description: string;
  is_in_stock: boolean;
  prices: { price: string; currency_code: string; currency_minor_unit: number };
}

export async function searchProducts(query: string, perPage = 10): Promise<Product[]> {
  const q = new URLSearchParams({ search: query, per_page: String(perPage) });
  return storeApiFetch(\`/products?\${q.toString()}\`);
}

export async function getProduct(id: number): Promise<Product> {
  return storeApiFetch(\`/products/\${id}\`);
}

export interface CartItem {
  key: string;
  id: number;
  name: string;
  quantity: number;
  prices: { price: string };
}

export interface Cart {
  items: CartItem[];
  totals: Record<string, unknown>;
}

export async function getCart(): Promise<Cart> {
  return storeApiFetch("/cart");
}

export async function addToCart(id: number, quantity: number): Promise<Cart> {
  return storeApiFetch("/cart/add-item", { method: "POST", body: JSON.stringify({ id, quantity }) });
}

export async function updateCartItem(key: string, quantity: number): Promise<Cart> {
  return storeApiFetch("/cart/update-item", { method: "POST", body: JSON.stringify({ key, quantity }) });
}

export async function removeCartItem(key: string): Promise<Cart> {
  return storeApiFetch("/cart/remove-item", { method: "POST", body: JSON.stringify({ key }) });
}
`;
}

function serverTs(): string {
  return `/**
 * Adeptra Merchant — WooCommerce MCP Shopping Server.
 *
 * Makes this store's catalog searchable and its cart buildable by an MCP-
 * speaking AI shopping agent. HARD BOUNDARY: this server never processes
 * payment. begin_checkout returns the current cart plus this store's normal
 * checkout URL — the agent/shopper hands off to your store's own checkout
 * from there. No /wc/store/v1/checkout call, no /wc/v3/ (admin) call, anywhere
 * in this file or woocommerce.ts.
 */

import "./loadEnv.js"; // MUST be the first import — see loadEnv.ts's header

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { searchProducts, getProduct, getCart, addToCart, updateCartItem, removeCartItem } from "./woocommerce.js";

const STORE_URL = process.env.WOOCOMMERCE_STORE_URL;
if (!STORE_URL) {
  console.error("Set WOOCOMMERCE_STORE_URL in .env (see .env.example) before starting this server.");
  process.exit(1);
}
const CHECKOUT_PATH = process.env.WOOCOMMERCE_CHECKOUT_PATH || "/checkout/";

const server = new McpServer({ name: "woocommerce-shopping-server", version: "1.0.0" });

function textResult(data: unknown) {
  return { content: [{ type: "text" as const, text: JSON.stringify(data, null, 2) }] };
}

${TOOL_ANNOTATIONS_NOTE}

server.registerTool(
  "search_products",
  {
    title: "Search products",
    description: "Search this store's product catalog by keyword.",
    inputSchema: {
      query: z.string().describe("Search text, e.g. product name or keyword"),
      limit: z.number().int().min(1).max(50).optional(),
    },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: true },
  },
  async ({ query, limit }) => textResult(await searchProducts(query, limit ?? 10)),
);

server.registerTool(
  "get_product",
  {
    title: "Get product",
    description: "Get full details for one product by its numeric id.",
    inputSchema: { id: z.number().int() },
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: true },
  },
  async ({ id }) => textResult(await getProduct(id)),
);

server.registerTool(
  "add_to_cart",
  {
    title: "Add to cart",
    description: "Add a product to the shopping cart.",
    inputSchema: { id: z.number().int(), quantity: z.number().int().min(1).default(1) },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  },
  async ({ id, quantity }) => textResult(await addToCart(id, quantity)),
);

server.registerTool(
  "update_cart_item",
  {
    title: "Update cart item",
    description: "Change the quantity of an existing cart line item.",
    inputSchema: {
      key: z.string().describe("The cart item's key, from get_cart/add_to_cart output"),
      quantity: z.number().int().min(1),
    },
    annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: true },
  },
  async ({ key, quantity }) => textResult(await updateCartItem(key, quantity)),
);

server.registerTool(
  "remove_cart_item",
  {
    title: "Remove cart item",
    description: "Remove a line item from the cart.",
    inputSchema: { key: z.string().describe("The cart item's key, from get_cart/add_to_cart output") },
    annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: true },
  },
  async ({ key }) => textResult(await removeCartItem(key)),
);

server.registerTool(
  "get_cart",
  {
    title: "Get cart",
    description: "Get the current cart contents and totals.",
    inputSchema: {},
    annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: true },
  },
  async () => textResult(await getCart()),
);

server.registerTool(
  "begin_checkout",
  {
    title: "Begin checkout",
    description:
      "Returns the current cart summary and this store's normal checkout URL. Does NOT process payment — hand off to checkout_url for the shopper to complete their purchase on the store's own site.",
    inputSchema: {},
    annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  },
  async () => {
    const cart = await getCart();
    return textResult({
      cart,
      checkout_url: \`\${STORE_URL!.replace(/\\/+$/, "")}\${CHECKOUT_PATH}\`,
      note: "Payment is not handled by this server — complete the purchase at checkout_url.",
    });
  },
);

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("WooCommerce MCP shopping server running (stdio).");
`;
}

function readmeMd(ctx: ArtifactContext): string {
  const label = storeLabel(ctx);
  return `# WooCommerce MCP Shopping Server

Generated by Adeptra Merchant for **${label}**.

## What this is

An MCP (Model Context Protocol) server that lets an AI shopping agent search
this store's product catalog and build a cart, using WooCommerce's built-in
Store API.

## The hard boundary — read this first

**This server reads your catalog and builds carts. It never takes payment —
checkout stays on your store.** Nothing in this server calls WooCommerce's
checkout/payment endpoints or exposes admin data. The \`begin_checkout\` tool
returns the current cart plus your store's normal checkout URL; the shopper
(or the agent, on the shopper's behalf) completes the purchase there, through
your existing payment setup. Adeptra generated and configured this server —
it does not host it, and it never touches your money.

${ucpConformanceDisclosure()}
## Prerequisites

- Node.js 18 or later, on a host you control (a VPS, a small cloud instance,
  a container — anywhere that can run a long-lived Node process). Adeptra
  never hosts this for you.
- Your store must expose the WooCommerce Store API (standard on modern
  WooCommerce/WooCommerce Blocks). Verify with:
  \`curl https://yourstore.example.com/wp-json/wc/store/v1/products\`
  You should get back a JSON array, not a 404 or a login page.

## Install

\`\`\`bash
cd mcp-server
npm install
npm run build
\`\`\`

## Configure

\`\`\`bash
cp .env.example .env
\`\`\`

Edit \`.env\` and set \`WOOCOMMERCE_STORE_URL\` to your real store URL. No API
key or secret is required — the Store API's catalog and cart endpoints are
public/unauthenticated by design (that's also why this server can't touch
payment or admin data: it was never given the keys to).

## Run

\`\`\`bash
npm start
\`\`\`

This starts the MCP server over stdio — the standard way MCP clients (agent
runtimes, UCP-speaking hosts) launch and talk to a local MCP server process.

## Connect it to your UCP manifest

Once this server is deployed somewhere reachable, point your UCP manifest's
\`dev.ucp.shopping\` service endpoint at its deployed address (replacing the
placeholder Adeptra's manifest fix left there), so agents that discover your
manifest know where to reach this shopping server.

## You must complete

- [ ] Deploy this to a host you control — Adeptra does not host it for you.
- [ ] Set the real \`WOOCOMMERCE_STORE_URL\` in \`.env\`.
- [ ] Confirm the Store API responds (see Prerequisites above).
- [ ] Point your UCP manifest's shopping service endpoint at this server's
      deployed address, then re-run your Adeptra analysis — that's what turns
      "cart/catalog/checkout capability enabled once deployed" into a genuine pass.

## Tools this server exposes

| Tool | Does |
|---|---|
| \`search_products\` | Search the catalog by keyword |
| \`get_product\` | Get one product's full details by id |
| \`add_to_cart\` | Add a product to the cart |
| \`update_cart_item\` | Change a cart line item's quantity |
| \`remove_cart_item\` | Remove a cart line item |
| \`get_cart\` | Get current cart contents + totals |
| \`begin_checkout\` | Return the cart + your store's checkout URL (no payment) |
`;
}

export function build(ctx: ArtifactContext): ScaffoldProvider {
  const files: ArtifactFile[] = [
    { path: "README.md", contents: readmeMd(ctx) },
    { path: "package.json", contents: packageJson() },
    { path: "tsconfig.json", contents: tsconfigJson() },
    { path: ".env.example", contents: envExample() },
    { path: "src/loadEnv.ts", contents: loadEnvTs() },
    { path: "src/server.ts", contents: serverTs() },
    { path: "src/woocommerce.ts", contents: woocommerceTs() },
  ];

  return {
    files,
    addedLines: [
      "mcp-server/README.md — deploy guide and the payment boundary, in plain English",
      "mcp-server/package.json — Node project (@modelcontextprotocol/sdk + zod only)",
      "mcp-server/tsconfig.json — build config for `npm run build`",
      "mcp-server/.env.example — WOOCOMMERCE_STORE_URL placeholder (no API key needed)",
      "mcp-server/src/loadEnv.ts — loads .env before anything else (must be the first import in server.ts)",
      "mcp-server/src/server.ts — MCP tools: search_products, get_product, add_to_cart, update_cart_item, remove_cart_item, get_cart, begin_checkout",
      "mcp-server/src/woocommerce.ts — WooCommerce Store API client (catalog + cart only; no payment, no admin API)",
    ],
    setupMustComplete: [
      "Set WOOCOMMERCE_STORE_URL in mcp-server/.env to your real store URL.",
      "Confirm your store exposes the WooCommerce Store API (GET /wp-json/wc/store/v1/products should return JSON) — standard on modern WooCommerce, but verify since some hosts/security plugins block wp-json routes.",
    ],
    extraFlagged: [],
  };
}
